on:
  pull_request:
    types: [closed]
    branches:
    - "master"

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  
    - name: delete branch
      uses: SvanBoxel/delete-merged-branch@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    