name: Build and release Docker images
on:
  push:
    branches:
      - master
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - name: Publish to Registry
      #   uses: sergeysova/docker-publish-action@master
      #   id: action
      #   with:
      #     image: registry.digitalocean.com/lls/helloworld
      #     registry: registry.digitalocean.com
      #     workdir: projects/helloworld
      #     username: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      #     password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      #     tag_semver: skip
      #     semver_higher: true
      #     tag_from_label: v1.0.0
      # - run: echo "${{ steps.action.outputs.digest }} / ${{ steps.action.outputs.tag }} / ${{ steps.action.outputs.semver }}"    
      # - name: Login to registry.digitalocean.com registry
      #   run: |
      #     echo ${{ secrets. DIGITALOCEAN_ACCESS_TOKEN }} | docker login --username ${{ secrets. DIGITALOCEAN_ACCESS_TOKEN }} --password-stdin registry.digitalocean.com

       
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: registry.digitalocean.com/lls/helloworld
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./projects/helloworld
          push: ${{ github.event_name != 'push tag' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}