name: Build and release Docker images
on:
  push:
    branches:
      - master
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2

      # - name: Publish to Registry
      #   uses: sergeysova/docker-publish-action@master
      #   id: action
      #   with:
      #     image: registry.digitalocean.com/lls/helloworld
      #     registry: registry.digitalocean.com
      #     workdir: projects/helloworld
      #     username: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      #     password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      #     tag_semver: skip
      #     semver_higher: true
      #     tag_from_label: v1.0.0
      # - run: echo "${{ steps.action.outputs.digest }} / ${{ steps.action.outputs.tag }} / ${{ steps.action.outputs.semver }}"    
      - name: Login to registry.digitalocean.com registry
        run: |
          echo ${{ secrets. DIGITALOCEAN_ACCESS_TOKEN }} | docker login --username ${{ secrets. DIGITALOCEAN_ACCESS_TOKEN }} --password-stdin registry.digitalocean.com

      - name: Build image
        run: |
          docker build -f projects/helloworld/Dockerfile -t registry.digitalocean.com/lls/helloworld:latest .

      - uses: weseek/ghaction-docker-tags-by-semver@v1.0.5
        with:
          source: 'registry.digitalocean.com/lls/helloworld'
          target: registry.digitalocean.com/lls/helloworld
          semver: '1.2.3'
          publish: true