name: Build and release Docker images
on:
  push:
    branches:
      - master
    tags:
    - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Publish to Registry
        uses: sergeysova/docker-publish-action@v1.0.0
        with:
          image: registry.digitalocean.com/lls/helloworld
          registry: registry.digitalocean.com
          workdir: projects/helloworld
          username: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          tag_semver: skip
          semver_higher: true
